# Generated by Django 2.2.1 on 2019-05-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
