# Generated by Django 2.2.1 on 2019-05-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
        ('posts', '0003_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(help_text='Categorize this item.', to='category.Category'),
        ),
    ]
