# Generated by Django 2.2.1 on 2019-05-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
    ]
