# Generated by Django 2.2.1 on 2019-05-22 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190522_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(help_text='Set prefered categories.', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 22, 21, 40, 36, 472891), null=True),
        ),
    ]
