# Generated by Django 2.2.1 on 2019-05-25 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190522_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Set prefered categories.', null=True, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 21, 15, 2, 274870), null=True),
        ),
    ]
