# Generated by Django 2.2.1 on 2019-05-25 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190525_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='http://ella.practicalaction.org/wp-content/themes/ella/images/no-photo.png'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 21, 39, 30, 512761), null=True),
        ),
    ]
