# Generated by Django 2.2.1 on 2019-05-26 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190525_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 26, 21, 30, 39, 987697), null=True),
        ),
    ]
